  - name: Delete health monitor vLB
    openstack.cloud.lb_health_monitor:
      auth:
        auth_url: "{{ auth_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        project_name: "{{ project_name | default('admin') }}"
        user_domain_name: "{{ user_domain_name | default('Default') }}"
        project_domain_name: "{{ project_domain_name | default('Default') }}"
      name: "{{ health.name }}"
      pool: "{{ lb_pool.name }}"
      delay: "{{ health.delay }}"
      resp_timeout: "{{ health.timeout }}"
      max_retries: "{{ health.retry_up }}"
      state: absent