---
- name: Create service group
  a10_slb_service_group:
    name: "{{ lb_pool.name }}"
    protocol: "{{ lb_pool.protocol | lower }}"
    health_check: "{{ lb_pool.healthmonitor.name }}"
    health_check_disable: "{{ not lb_pool.healthmonitor.admin_state_up  }}"
    lb_method: "{{ 'round-robin' if lb_pool.lb_algorithm == 'ROUND_ROBIN' else
                   'src-ip-hash' if lb_pool.lb_algorithm == 'SOURCE_IP_PORT' else
                   'src-ip-only-hash' if lb_pool.lb_algorithm == 'SOURCE_IP' else omit }}"
    lc_method: "{{ 'least-connection' if lb_pool.lb_algorithm == 'LEAST_CONNECTIONS' else omit }}"
    state: present
  tags:
    - loadbalancer
    - pool

- name: Create backend servers and add to service group
  include_role:
    name: member
    apply:
      tags:
        - loadbalancer
        - pool
        - member
  loop: "{{ lb_pool.members }}"
  loop_control:
    loop_var: lb_member
  tags:
    - loadbalancer
    - pool
    - member

