---
- include_role:
    name: member
    apply:
      tags:
        - loadbalancer
        - pool
        - member
  loop: "{{ lb_pool.members }}"
  loop_control:
    loop_var: lb_member
  tags:
    - loadbalancer
    - pool
    - member

- name: Delete service group
  a10_slb_service_group:
    name: "{{ lb_pool.name }}"
    state: absent
  tags:
    - loadbalancer
    - pool

- include_role:
    name: healthmonitor
    apply:
      tags:
        - loadbalancer
        - pool
        - healthmonitor
  vars:
    health: "{{ lb_pool.healthmonitor }}"
  tags:
    - loadbalancer
    - pool
    - healthmonitor
