---
- name: Create pool vLB
  openstack.cloud.lb_pool:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name | default('admin') }}"
      user_domain_name: "{{ user_domain_name | default('Default') }}"
      project_domain_name: "{{ project_domain_name | default('Default') }}"
    name: "{{ lb_pool.name }}"
    loadbalancer: "{{ loadbalancer.name }}"
    protocol: "{{ lb_pool.protocol }}"
    lb_algorithm: "{{ lb_pool.lb_algorithm }}"
    state: present
  tags:
    - loadbalancer
    - pool

- include_role:
    name: healthmonitor
    apply:
      tags:
        - loadbalancer
        - pool
        - healthmonitor
  vars:
    health: "{{ lb_pool.healthmonitor }}"
  tags:
    - loadbalancer
    - pool
    - healthmonitor

- include_role:
    name: member
    apply:
      tags:
        - loadbalancer
        - pool
        - member
  loop: "{{ lb_pool.members }}"
  loop_control:
    loop_var: lb_member
  tags:
    - loadbalancer
    - pool
    - member

