---
- name: Delete listeners vLB
  openstack.cloud.lb_listener:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name | default('admin') }}"
      user_domain_name: "{{ user_domain_name | default('Default') }}"
      project_domain_name: "{{ project_domain_name | default('Default') }}"
    name: "{{ lb_listener.name }}"
    loadbalancer: "{{ loadbalancer.name }}"
    state: absent
