---
- name: Delete members of vLB
  openstack.cloud.lb_member:
    auth:
      auth_url: "{{ auth_url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name | default('admin') }}"
      user_domain_name: "{{ user_domain_name | default('Default') }}"
      project_domain_name: "{{ project_domain_name | default('Default') }}"
    name: "{{ lb_member.name }}"
    pool: "{{ lb_pool.name }}"
    address: "{{ lb_member.address }}"
    protocol_port: "{{ lb_pool.protocol_port }}"
    state: absent